# List of plugins
set -g @plugin 'tmux-plugins/tpm'

set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'

set -g @plugin 'alexwforsythe/tmux-which-key'
set -g @plugin 'thepante/tmux-git-autofetch'
# set -g @plugin 'kiyoon/treemux' # Check this one out once you have use nvim for a bit
# set -g @plugin 'olimorris/tmux-pomodoro-plus'

set -g @plugin '2kabhishek/tmux2k'

# Settings
set -g default-shell "$HOME/.nix-profile/bin/fish"
set -g mouse on
unbind -n MouseDown3Pane

set -g @continuum-restore 'on'

set -g @tmux2k-left-sep 
set -g @tmux2k-right-sep 
set -g @tmux2k-window-list-left-sep 
set -g @tmux2k-window-list-right-sep 
set -g @tmux2k-window-list-format "#{b:pane_current_path}"

set -g @tmux2k-black '#24273a'
set -g @tmux2k-gray '#363a4f'
set -g @tmux2k-white '#fffaf3'
set -g @tmux2k-light-blue '#89dceb'
set -g @tmux2k-blue '#89dceb'
set -g @tmux2k-dark-blue '#04a5e5'
set -g @tmux2k-light-green '#a6e3a1'
set -g @tmux2k-green '#a6e3a1'
set -g @tmux2k-dark-green '#40a02b'
set -g @tmux2k-light-yellow '#eed49f'
set -g @tmux2k-yellow '#eed49f'
set -g @tmux2k-dark-yellow '#df8e1d'
set -g @tmux2k-light-orange '#f5a97f'
set -g @tmux2k-orange '#f5a97f'
set -g @tmux2k-dark-orange '#fe640b'
set -g @tmux2k-light-red '#ee99a0'
set -g @tmux2k-red '#ee99a0'
set -g @tmux2k-dark-red '#e64553'
set -g @tmux2k-light-pink '#f5bde6'
set -g @tmux2k-pink '#f5bde6'
set -g @tmux2k-dark-pink '#ea76cb'
set -g @tmux2k-light-purple '#c6a0f6'
set -g @tmux2k-purple '#c6a0f6'
set -g @tmux2k-dark-purple '#8839ef'

set -gu @tmux2k-bg-alt '#f5a97f'
set -gu @tmux2k-message-bg '#f5a97f'
set -g @tmux2k-pane-active-border '#f5a97f'
set -g @tmux2k-pane-active-border-bg 'default'
set -g @tmux2k-pane-border_bg 'default'
set -g @tmux2k-prefix-highlight '#f5a97f'

set -g @tmux2k-window-list-colors 'black red'

set -g mode-style "fg=#24273a,bg=#f5a97f"


# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
